# Generated by Django 4.1.3 on 2022-11-30 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField(null=True)),
                ('stock', models.IntegerField(null=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
